internal_ops:
  artifact_dir : artifacts
  dumpeddir: fileNamespkl
  src_pkl_filename: filenames.pkl
  messed_dirPath: ./images # provide the dirpath which you want to arrange
  PredictionImgDir: predImgDir # provide the predImgPath 
  input : none 
  ExtractedFeatures:
    imgfeaturesdir : embeddingImgdata
    imgFeaturesFilename: features_embedding.pkl
  


  
